"""Add user_id to Order model with named constraint

Revision ID: b6068dba846a
Revises: f2a90e431f49
Create Date: 2025-05-19 14:05:04.613150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6068dba846a'
down_revision = 'f2a90e431f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
    constraint_name='fk_order_user_id',
    referent_table='user',
    local_cols=['user_id'],
    remote_cols=['id']
)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
