"""Add table_id to Order model

Revision ID: d1e2f3a4b5c6
Revises: b6068dba846a
Create Date: 2025-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e2f3a4b5c6'
down_revision = 'b6068dba846a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            constraint_name='fk_order_table_id',
            referent_table='table',
            local_cols=['table_id'],
            remote_cols=['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_table_id', type_='foreignkey')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###

